import { Inter } from "next/font/google";
import "./globals.css";
// import localFont from "next/font/local"

// const Poppins = localFont({
//   src: [
//     {
//       path: '../assets/fonts/Poppins-Light.ttf',
//       weight: '300',
//       style: 'normal',
//     },
//     {
//       path: '../assets/fonts/Poppins-Regular.ttf',
//       weight: '400',
//       style: 'normal',
//     },
//     {
//       path: '../assets/fonts/Poppins-Medium.ttf',
//       weight: '500',
//       style: 'normal',
//     },
//     {
//       path: '../assets/fonts/Poppins-SemiBold.ttf',
//       weight: '600',
//       style: 'normal',
//     },
//     {
//       path: '../assets/fonts/Poppins-Bold.ttf',
//       weight: '700',
//       style: 'normal',
//     },
//   ],
// })
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
